M48
; DRILL file {KiCad 8.0.4} date 2024-09-13T16:29:25+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-13T16:29:25+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X39.0Y-119.0
X39.1Y-165.9
X102.6Y-119.2
X102.6Y-165.7
X230.9Y-119.1
X231.0Y-166.0
M30
