M48
; DRILL file {KiCad 8.0.4} date 2024-09-13T15:55:04+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-13T15:55:04+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X239.0Y-166.0
X239.15Y-119.05
X355.9Y-165.908
X356.0Y-118.908
M30
